In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [3]:
df = pd.read_csv('/Users/takahashikaisei/Lecture/ds_programing/final_kadai/local_data/screantime_data.csv')
df

           ymd  sns  game  youtube
0   2023/12/10  222   160      159
1   2023/12/11  119    52      311
2   2023/12/12   60     0      391
3   2023/12/13  177   119      138
4   2023/12/14  179     8      413
5   2023/12/15  138     8      182
6   2023/12/16   74    56      429
7   2023/12/17  138    67      560
8   2023/12/18   31     0      201
9   2023/12/19   73    24      435
10  2023/12/20   59     0      524
11  2023/12/21   42     0      460
12  2023/12/22   58     0      327
13  2023/12/23   56    22      381
14  2023/12/24   90     0      247
15  2023/12/25  114     0      451
16  2023/12/26  146    25      254
17  2023/12/27  120     6      365
18  2023/12/28   82     0      275
19  2023/12/29  115     3      237
20  2023/12/30  241   170      186
21  2023/12/31   97    72      146
22    2024/1/1  214    25      268
23    2024/1/2  164   221      292
24    2024/1/3   96    91      111
25    2024/1/4  132     0      321
26    2024/1/5  167    27      183
27    2024/1/6  365     0      208
28    2024/1/7  210     0      736
29    2024/1/8  273     0      415
30    2024/1/9  131     9      248
31   2024/1/10   95     0      361
32   2024/1/11  128     0      208
33   2024/1/12  117    32      345
34   2024/1/13  109    21      299